
PROGS = myftp myftpd
DEP = l4c.o my_error.o my_socket.o

CC=gcc
CFLAGS = -O2

%.o : %.c
	$(CC) $(CFLAGS) -c $<

all:	${PROGS}

dep:	${DEP}

myftp:	myftp.o
	${CC} ${CFLAGS} -o $@ myftp.o ${DEP}

myftpd:	myftpd.o ${DEP}
	${CC} ${CFLAGS} -o $@ myftpd.o ${DEP}

clean:
	/bin/rm -f ${PROGS} *.o ~* *.stackdump
	chmod 664 *.c *.h

rm:
	/bin/rm -f *.o ~* *.stackdump
	chmod 664 *.c *.h

