
# This is CPAN.pm's systemwide configuration file. This file provides
# defaults for users, and the values can be changed in a per-user
# configuration file. The user-config file is being looked for as
# /Users/mferreira/.cpan/CPAN/MyConfig.pm.

$CPAN::Config = {
    'applypatch'                     =>  q[],
    'auto_commit'                    =>  q[0],
    'build_cache'                    =>  q[100],
    'build_dir'                      =>  q[/pub/src/perl/cpan/build],
    'build_dir_reuse'                =>  q[0],
    'build_requires_install_policy'  =>  q[yes],
    'bzip2'                          =>  q[/usr/bin/bzip2],
    'cache_metadata'                 =>  q[1],
    'check_sigs'                     =>  q[0],
    'commandnumber_in_prompt'        =>  q[1],
    'connect_to_internet_ok'         =>  q[1],
    'cpan_home'                      =>  q[/pub/src/perl/cpan],
    'curl'                           =>  q[/usr/bin/curl],
    'ftp'                            =>  q[/usr/bin/ftp],
    'ftp_passive'                    =>  q[1],
    'ftp_proxy'                      =>  q[],
    'getcwd'                         =>  q[cwd],
    'gpg'                            =>  q[/opt/local/bin/gpg],
    'gzip'                           =>  q[/usr/bin/gzip],
    'halt_on_failure'                =>  q[0],
    'histfile'                       =>  q[/pub/src/perl/cpan/histfile],
    'histsize'                       =>  q[100],
    'http_proxy'                     =>  q[],
    'inactivity_timeout'             =>  q[0],
    'index_expire'                   =>  q[1],
    'inhibit_startup_message'        =>  q[0],
    'keep_source_where'              =>  q[/pub/src/perl/cpan/sources],
    'load_module_verbosity'          =>  q[v],
    'lynx'                           =>  q[/opt/local/bin/lynx],
    'make'                           =>  q[/usr/bin/make],
    'make_arg'                       =>  q[],
    'make_install_arg'               =>  q[],
    'make_install_make_command'      =>  q[/usr/bin/make],
    'makepl_arg'                     =>  q[],
    'mbuild_arg'                     =>  q[],
    'mbuild_install_arg'             =>  q[],
    'mbuild_install_build_command'   =>  q[./Build],
    'mbuildpl_arg'                   =>  q[],
    'ncftpget'                       =>  q[],
    'no_proxy'                       =>  q[],
    'pager'                          =>  q[/usr/bin/less],
    'patch'                          =>  q[/usr/bin/patch],
    'perl5lib_verbosity'             =>  q[v],
    'prefer_installer'               =>  q[MB],
    'prefs_dir'                      =>  q[/pub/src/perl/cpan/prefs],
    'prerequisites_policy'           =>  q[follow],
    'scan_cache'                     =>  q[atstart],
    'shell'                          =>  q[/bin/bash],
    'show_unparsable_versions'       =>  q[0],
    'show_upload_date'               =>  q[1],
    'show_zero_versions'             =>  q[0],
    'tar'                            =>  q[/usr/bin/tar],
    'tar_verbosity'                  =>  q[v],
    'term_is_latin'                  =>  q[1],
    'term_ornaments'                 =>  q[1],
    'test_report'                    =>  q[1],
    'trust_test_report_history'      =>  q[1],
    'unzip'                          =>  q[/usr/bin/unzip],
    'urllist'                        =>  [ q[ftp://ftp.pucpr.br/CPAN]
                                         , q[ftp://cpan.cs.utah.edu/pub/CPAN/]
                                         , q[ftp://ftp.linorg.usp.br/CPAN]
                                         ],
    'use_sqlite'                     =>  q[1],
    'wget'                           =>  q[/opt/local/bin/wget],
    'yaml_load_code'                 =>  q[0],
    'yaml_module'                    =>  q[YAML],
};
1;
__END__
