#
#
#

ORACLE_BASE=c:\\oracle
ORACLE_HOME=/u01/app/oracle/product/8.1.7
ORACLE_HOME=c:\\oracle\\ora92
ORACLE_SID=orcl
ORACLE_USERID=scott/tiger@orcl

NLS_DATE_FORMAT="dd/mm/yyyy hh24:mi:ss"
NLS_LANG="AMERICAN_AMERICA.WE8ISO8859P1"

export ORACLE_BASE ORACLE_HOME ORACLE_SID ORACLE_USERID 
export NLS_DATE_FORMAT NLS_LANG

